# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clerk_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label.setObjectName("label")
        self.clk_del_pb = QtWidgets.QPushButton(Dialog)
        self.clk_del_pb.setGeometry(QtCore.QRect(246, 90, 75, 23))
        self.clk_del_pb.setObjectName("clk_del_pb")
        self.clk_up_pb = QtWidgets.QPushButton(Dialog)
        self.clk_up_pb.setGeometry(QtCore.QRect(246, 130, 75, 23))
        self.clk_up_pb.setObjectName("clk_up_pb")
        self.clk_down_pb = QtWidgets.QPushButton(Dialog)
        self.clk_down_pb.setGeometry(QtCore.QRect(246, 170, 75, 23))
        self.clk_down_pb.setObjectName("clk_down_pb")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(338, 20, 54, 12))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(331, 50, 16, 171))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(338, 41, 201, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(338, 210, 201, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(348, 70, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(348, 100, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(348, 130, 54, 12))
        self.label_5.setObjectName("label_5")
        self.clk_seq_le = QtWidgets.QLineEdit(Dialog)
        self.clk_seq_le.setGeometry(QtCore.QRect(388, 67, 61, 20))
        self.clk_seq_le.setObjectName("clk_seq_le")
        self.clk_name_le = QtWidgets.QLineEdit(Dialog)
        self.clk_name_le.setGeometry(QtCore.QRect(388, 97, 91, 20))
        self.clk_name_le.setObjectName("clk_name_le")
        self.clerk_dpt_comboBox = QtWidgets.QComboBox(Dialog)
        self.clerk_dpt_comboBox.setGeometry(QtCore.QRect(388, 127, 121, 22))
        self.clerk_dpt_comboBox.setObjectName("clerk_dpt_comboBox")
        self.clk_add_pb = QtWidgets.QPushButton(Dialog)
        self.clk_add_pb.setGeometry(QtCore.QRect(348, 171, 61, 31))
        self.clk_add_pb.setObjectName("clk_add_pb")
        self.clk_modify_pb = QtWidgets.QPushButton(Dialog)
        self.clk_modify_pb.setGeometry(QtCore.QRect(408, 171, 61, 31))
        self.clk_modify_pb.setObjectName("clk_modify_pb")
        self.clk_save_pb = QtWidgets.QPushButton(Dialog)
        self.clk_save_pb.setGeometry(QtCore.QRect(468, 171, 61, 31))
        self.clk_save_pb.setObjectName("clk_save_pb")
        self.clk_quit_pb = QtWidgets.QPushButton(Dialog)
        self.clk_quit_pb.setGeometry(QtCore.QRect(468, 260, 75, 23))
        self.clk_quit_pb.setObjectName("clk_quit_pb")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(530, 49, 16, 171))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 211, 201))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "职员管理"))
        self.label.setText(_translate("Dialog", "姓名："))
        self.clk_del_pb.setText(_translate("Dialog", "删除"))
        self.clk_up_pb.setText(_translate("Dialog", "上移"))
        self.clk_down_pb.setText(_translate("Dialog", "下移"))
        self.label_2.setText(_translate("Dialog", "基本信息："))
        self.label_3.setText(_translate("Dialog", "序号："))
        self.label_4.setText(_translate("Dialog", "姓名："))
        self.label_5.setText(_translate("Dialog", "部门："))
        self.clk_add_pb.setText(_translate("Dialog", "增加职员"))
        self.clk_modify_pb.setText(_translate("Dialog", "修改信息"))
        self.clk_save_pb.setText(_translate("Dialog", "保存"))
        self.clk_quit_pb.setText(_translate("Dialog", "退出"))

