# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, -1, 1011, 678))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(20, 120, 161, 521))
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(50, 1, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(50, 420, 54, 12))
        self.label_6.setObjectName("label_6")
        self.layoutWidget = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 230, 151, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.show_dpt_tb = QtWidgets.QToolButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/显示部门.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_dpt_tb.setIcon(icon)
        self.show_dpt_tb.setIconSize(QtCore.QSize(128, 128))
        self.show_dpt_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.show_dpt_tb.setObjectName("show_dpt_tb")
        self.gridLayout_2.addWidget(self.show_dpt_tb, 0, 0, 1, 1)
        self.hide_dpt_tb = QtWidgets.QToolButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/隐藏部门.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hide_dpt_tb.setIcon(icon1)
        self.hide_dpt_tb.setIconSize(QtCore.QSize(128, 128))
        self.hide_dpt_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.hide_dpt_tb.setObjectName("hide_dpt_tb")
        self.gridLayout_2.addWidget(self.hide_dpt_tb, 0, 1, 1, 1)
        self.cancel_freeze_tb = QtWidgets.QToolButton(self.layoutWidget)
        self.cancel_freeze_tb.setIcon(icon)
        self.cancel_freeze_tb.setIconSize(QtCore.QSize(128, 128))
        self.cancel_freeze_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.cancel_freeze_tb.setObjectName("cancel_freeze_tb")
        self.gridLayout_2.addWidget(self.cancel_freeze_tb, 1, 0, 1, 1)
        self.freeze_tb = QtWidgets.QToolButton(self.layoutWidget)
        self.freeze_tb.setIcon(icon)
        self.freeze_tb.setIconSize(QtCore.QSize(128, 128))
        self.freeze_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.freeze_tb.setObjectName("freeze_tb")
        self.gridLayout_2.addWidget(self.freeze_tb, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 440, 151, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.query_tb = QtWidgets.QToolButton(self.layoutWidget1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/单位名称.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.query_tb.setIcon(icon2)
        self.query_tb.setIconSize(QtCore.QSize(128, 128))
        self.query_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.query_tb.setObjectName("query_tb")
        self.horizontalLayout_3.addWidget(self.query_tb)
        self.statistic_tb = QtWidgets.QToolButton(self.layoutWidget1)
        self.statistic_tb.setIcon(icon2)
        self.statistic_tb.setIconSize(QtCore.QSize(128, 128))
        self.statistic_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.statistic_tb.setObjectName("statistic_tb")
        self.horizontalLayout_3.addWidget(self.statistic_tb)
        self.about_tb = QtWidgets.QToolButton(self.widget)
        self.about_tb.setGeometry(QtCore.QRect(930, 0, 71, 81))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/关于.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_tb.setIcon(icon3)
        self.about_tb.setIconSize(QtCore.QSize(128, 128))
        self.about_tb.setCheckable(False)
        self.about_tb.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.about_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.about_tb.setObjectName("about_tb")
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setGeometry(QtCore.QRect(200, 130, 801, 521))
        self.tableView.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.tableView.setObjectName("tableView")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(20, 105, 981, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(170, 106, 20, 551))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.widget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 0, 281, 101))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.generate_payroll_tb = QtWidgets.QToolButton(self.layoutWidget2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/生成工资条.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_payroll_tb.setIcon(icon4)
        self.generate_payroll_tb.setIconSize(QtCore.QSize(128, 128))
        self.generate_payroll_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.generate_payroll_tb.setObjectName("generate_payroll_tb")
        self.horizontalLayout.addWidget(self.generate_payroll_tb)
        self.dpt_payroll_tb = QtWidgets.QToolButton(self.layoutWidget2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/部门工资表.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dpt_payroll_tb.setIcon(icon5)
        self.dpt_payroll_tb.setIconSize(QtCore.QSize(128, 128))
        self.dpt_payroll_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.dpt_payroll_tb.setObjectName("dpt_payroll_tb")
        self.horizontalLayout.addWidget(self.dpt_payroll_tb)
        self.export_current_payroll_tb = QtWidgets.QToolButton(self.layoutWidget2)
        self.export_current_payroll_tb.setIcon(icon5)
        self.export_current_payroll_tb.setIconSize(QtCore.QSize(128, 128))
        self.export_current_payroll_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.export_current_payroll_tb.setObjectName("export_current_payroll_tb")
        self.horizontalLayout.addWidget(self.export_current_payroll_tb)
        self.export_all_payroll_tb = QtWidgets.QToolButton(self.layoutWidget2)
        self.export_all_payroll_tb.setIcon(icon5)
        self.export_all_payroll_tb.setIconSize(QtCore.QSize(128, 128))
        self.export_all_payroll_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.export_all_payroll_tb.setObjectName("export_all_payroll_tb")
        self.horizontalLayout.addWidget(self.export_all_payroll_tb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.layoutWidget3 = QtWidgets.QWidget(self.widget)
        self.layoutWidget3.setGeometry(QtCore.QRect(340, 0, 551, 101))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.protect_tb = QtWidgets.QToolButton(self.layoutWidget3)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/保护工资表.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.protect_tb.setIcon(icon6)
        self.protect_tb.setIconSize(QtCore.QSize(128, 128))
        self.protect_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.protect_tb.setObjectName("protect_tb")
        self.horizontalLayout_2.addWidget(self.protect_tb)
        self.cancel_protect_tb = QtWidgets.QToolButton(self.layoutWidget3)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../images/取消保护工资表.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_protect_tb.setIcon(icon7)
        self.cancel_protect_tb.setIconSize(QtCore.QSize(128, 128))
        self.cancel_protect_tb.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.cancel_protect_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.cancel_protect_tb.setArrowType(QtCore.Qt.NoArrow)
        self.cancel_protect_tb.setObjectName("cancel_protect_tb")
        self.horizontalLayout_2.addWidget(self.cancel_protect_tb)
        self.add_extra_label_tb = QtWidgets.QToolButton(self.layoutWidget3)
        self.add_extra_label_tb.setIcon(icon6)
        self.add_extra_label_tb.setIconSize(QtCore.QSize(128, 128))
        self.add_extra_label_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.add_extra_label_tb.setObjectName("add_extra_label_tb")
        self.horizontalLayout_2.addWidget(self.add_extra_label_tb)
        self.del_extra_label_tb = QtWidgets.QToolButton(self.layoutWidget3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../images/删除当前工资表.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_extra_label_tb.setIcon(icon8)
        self.del_extra_label_tb.setIconSize(QtCore.QSize(128, 128))
        self.del_extra_label_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.del_extra_label_tb.setObjectName("del_extra_label_tb")
        self.horizontalLayout_2.addWidget(self.del_extra_label_tb)
        self.add_current_month_tb = QtWidgets.QToolButton(self.layoutWidget3)
        self.add_current_month_tb.setIcon(icon8)
        self.add_current_month_tb.setIconSize(QtCore.QSize(128, 128))
        self.add_current_month_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.add_current_month_tb.setObjectName("add_current_month_tb")
        self.horizontalLayout_2.addWidget(self.add_current_month_tb)
        self.del_current_month_tb = QtWidgets.QToolButton(self.layoutWidget3)
        self.del_current_month_tb.setIcon(icon8)
        self.del_current_month_tb.setIconSize(QtCore.QSize(128, 128))
        self.del_current_month_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.del_current_month_tb.setObjectName("del_current_month_tb")
        self.horizontalLayout_2.addWidget(self.del_current_month_tb)
        self.generate_next_tb = QtWidgets.QToolButton(self.layoutWidget3)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../images/生成下月工资表.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_next_tb.setIcon(icon9)
        self.generate_next_tb.setIconSize(QtCore.QSize(128, 128))
        self.generate_next_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.generate_next_tb.setObjectName("generate_next_tb")
        self.horizontalLayout_2.addWidget(self.generate_next_tb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.layoutWidget4 = QtWidgets.QWidget(self.widget)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 140, 151, 151))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.dpt_tb = QtWidgets.QToolButton(self.layoutWidget4)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../images/部门管理.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dpt_tb.setIcon(icon10)
        self.dpt_tb.setIconSize(QtCore.QSize(128, 128))
        self.dpt_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.dpt_tb.setObjectName("dpt_tb")
        self.gridLayout.addWidget(self.dpt_tb, 0, 1, 1, 1)
        self.prj_tb = QtWidgets.QToolButton(self.layoutWidget4)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../images/工资项目管理.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prj_tb.setIcon(icon11)
        self.prj_tb.setIconSize(QtCore.QSize(128, 128))
        self.prj_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.prj_tb.setObjectName("prj_tb")
        self.gridLayout.addWidget(self.prj_tb, 1, 0, 1, 1)
        self.unit_tb = QtWidgets.QToolButton(self.layoutWidget4)
        self.unit_tb.setIcon(icon2)
        self.unit_tb.setIconSize(QtCore.QSize(128, 128))
        self.unit_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.unit_tb.setObjectName("unit_tb")
        self.gridLayout.addWidget(self.unit_tb, 1, 1, 1, 1)
        self.clk_tb = QtWidgets.QToolButton(self.layoutWidget4)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../images/职工管理.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clk_tb.setIcon(icon12)
        self.clk_tb.setIconSize(QtCore.QSize(256, 512))
        self.clk_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.clk_tb.setObjectName("clk_tb")
        self.gridLayout.addWidget(self.clk_tb, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionEdit)
        self.menu_File.addAction(self.actionExit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "基础设置"))
        self.label_5.setText(_translate("MainWindow", "显示/隐藏"))
        self.label_6.setText(_translate("MainWindow", "查询/统计"))
        self.show_dpt_tb.setText(_translate("MainWindow", "显示部门"))
        self.hide_dpt_tb.setText(_translate("MainWindow", "隐藏部门"))
        self.cancel_freeze_tb.setText(_translate("MainWindow", "取消行冻\n"
"结标题"))
        self.freeze_tb.setText(_translate("MainWindow", "冻结行标题"))
        self.query_tb.setText(_translate("MainWindow", "查询"))
        self.statistic_tb.setText(_translate("MainWindow", "统计"))
        self.about_tb.setText(_translate("MainWindow", "关于"))
        self.generate_payroll_tb.setText(_translate("MainWindow", "生成工资表"))
        self.dpt_payroll_tb.setText(_translate("MainWindow", "部门工资表"))
        self.export_current_payroll_tb.setText(_translate("MainWindow", "导出当\n"
"前工资表"))
        self.export_all_payroll_tb.setText(_translate("MainWindow", "导出全部\n"
"工资表"))
        self.label.setText(_translate("MainWindow", "数据处理"))
        self.protect_tb.setText(_translate("MainWindow", "保护工资表"))
        self.cancel_protect_tb.setText(_translate("MainWindow", "取消保护\n"
"工资表"))
        self.add_extra_label_tb.setText(_translate("MainWindow", "增加附加表"))
        self.del_extra_label_tb.setText(_translate("MainWindow", "删除附加表"))
        self.add_current_month_tb.setText(_translate("MainWindow", "增加当月\n"
"工资表"))
        self.del_current_month_tb.setText(_translate("MainWindow", "删除当月\n"
"工资表"))
        self.generate_next_tb.setText(_translate("MainWindow", "生成下月\n"
"工资表"))
        self.label_2.setText(_translate("MainWindow", "工作表管理"))
        self.dpt_tb.setText(_translate("MainWindow", "部门管理"))
        self.prj_tb.setText(_translate("MainWindow", "工资项目"))
        self.unit_tb.setText(_translate("MainWindow", "单位名称"))
        self.clk_tb.setText(_translate("MainWindow", "职工管理"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))

